# Generated by Django 2.1 on 2018-11-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181118_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pglistings',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='pg_images'),
        ),
        migrations.AlterField(
            model_name='rentlistings',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='rent_images'),
        ),
        migrations.AlterField(
            model_name='selllistings',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='sell_images'),
        ),
    ]
